site_name: My Docs

markdown_extensions:
  - pymdownx.snippets:

nav:
    - 'index.md'

theme:
  name: material
  features:
   - toc.integrate

plugins:
    - techdocs-core
    # - pdf-export